// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDocPath() {
  return window['go']['main']['Config']['GetDocPath']();
}

export function SetDocPath(arg1) {
  return window['go']['main']['Config']['SetDocPath'](arg1);
}
