// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSession() {
  return window['go']['main']['Session']['DeleteSession']();
}

export function GetSession() {
  return window['go']['main']['Session']['GetSession']();
}

export function SetSession(arg1, arg2) {
  return window['go']['main']['Session']['SetSession'](arg1, arg2);
}
