// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteSession():Promise<void>;

export function GetSession():Promise<main.Session>;

export function SetSession(arg1:string,arg2:string):Promise<void>;
